model_params:
  vocab_size: 178
  hidden_size: 768
  num_attention_heads: 12
  intermediate_size: 2048
  max_position_embeddings: 512
  num_hidden_layers: 12
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
